import { MoreHorizontal, Plus } from 'lucide-react';
import { Area, AreaChart, ResponsiveContainer } from 'recharts';
import { useTranslation } from 'react-i18next';
import { watchlist } from '@/data/stockMockData';

export function Watchlist({ selectedTicker, onSelectTicker }: { selectedTicker: string; onSelectTicker: (ticker: string) => void }) {
  const { t } = useTranslation();
  return <aside className="rounded-2xl border border-slate-800 bg-[#111827] shadow-xl shadow-black/10 xl:sticky xl:top-24"><header className="flex items-center justify-between border-b border-slate-800 p-4"><div><h2 className="font-bold text-white">{t('stock.myStocks')}</h2><p className="mt-1 text-xs text-slate-500">{watchlist.length} {t('stock.symbols')}</p></div><button type="button" aria-label={t('stock.addStock')} className="flex size-10 items-center justify-center rounded-xl bg-blue-600 text-white transition hover:bg-blue-500"><Plus size={18}/></button></header><div className="max-h-[760px] overflow-y-auto overscroll-contain p-2">{watchlist.map(stock => { const positive=stock.change>=0; const active=stock.ticker===selectedTicker; const data=stock.sparkline.map((value,index)=>({index,value})); const gradientId=`spark-${stock.ticker}`; return <button type="button" key={stock.ticker} aria-pressed={active} onClick={() => onSelectTicker(stock.ticker)} className={`grid w-full grid-cols-[minmax(0,1fr)_72px_auto] items-center gap-3 rounded-xl border-l-2 px-3 py-3 text-left transition ${active ? 'border-l-blue-500 bg-blue-500/10' : 'border-l-transparent hover:bg-slate-800/70'}`}><div className="min-w-0"><p className={`font-bold ${active ? 'text-blue-400' : 'text-slate-100'}`}>{stock.ticker}</p><p className="truncate text-xs text-slate-500">{stock.company}</p></div><div className="h-10"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs><linearGradient id={gradientId} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={positive?'#10B981':'#EF4444'} stopOpacity={0.15}/><stop offset="100%" stopColor={positive?'#10B981':'#EF4444'} stopOpacity={0}/></linearGradient></defs><Area type="monotone" dataKey="value" stroke={positive?'#10B981':'#EF4444'} strokeWidth={2} fill={`url(#${gradientId})`} dot={false}/></AreaChart></ResponsiveContainer></div><div className="text-right"><p className="text-sm font-semibold text-slate-200">${stock.price.toFixed(2)}</p><p className={`text-xs font-semibold ${positive?'text-emerald-400':'text-red-400'}`}>{positive?'+':''}{stock.change.toFixed(2)}%</p></div></button>; })}</div><button type="button" className="flex min-h-11 w-full items-center justify-center gap-2 border-t border-slate-800 text-xs font-semibold text-slate-500 hover:text-white"><MoreHorizontal size={17}/>{t('stock.manageWatchlist')}</button></aside>;
}
